spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring
    username: spring
    password: password
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  profiles:
    active: default
  application:
    name: product-service

server:
  port: 8002

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream