spring:
  profiles:
    active: default
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/spring
    username: spring
    password: password
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8005

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

jwt:
  secret: secret