spring:
  profiles:
    active: default
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://mysql/spring
    username: spring
    password: password
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8005

eureka:
  client:
    service-url:
      default-zone: http://server/eureka

jwt:
  secret: secret