spring:
  datasource:
    url: jdbc:mysql://mysql/spring
    username: spring
    password: password
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  profiles:
    active: default
  application:
    name: cart-service

server:
  port: 8003

eureka:
  client:
    service-url:
      default-zone: http://server/eureka

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream